trigger:
- develop

variables:
  solution: 'WorldOfDarkNet.sln'

jobs:
- job: API
  displayName: Build API
  pool:
    vmImage: 'windows-latest'

  steps:
  - task: UseDotNet@2
    displayName: 'Configure .net core version 3.0.x'
    inputs:
      version: '3.0.x'

  - task: DotNetCoreCLI@2
    displayName: dotnet build
    inputs:
      projects: '$(solution)'

  - task: DotNetCoreCLI@2
    displayName: dotnet publish
    inputs:
      command: publish
      publishWebProjects: True
      arguments: ' --output $(build.artifactstagingdirectory)'
      zipAfterPublish: True

  - task: PublishBuildArtifacts@1
    displayName: 'Publish API artifact'
    inputs:
      pathtoPublish: '$(build.artifactstagingdirectory)'
      artifactName: 'API'
      publishLocation: 'Container'