version: '3'

services:
  pgdb_darknet:
    image: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - ~/darknet/data:/var/lib/postgresql/data
      - ~/darknet/conf:/etc/postgresql
      - ~/darknet/log:/var/log/postgresql
    environment:
      - POSTGRES_DB=worldofdb
      - POSTGRES_PASSWORD=123456

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8082:8080